name: lifecycle_capsules
description: Easily manage lifecycle-aware objects and operations in Flutter, preventing code duplication and simplifying resource handling.
version: 1.0.3-beta.3
homepage: https://github.com/BaselMoustafa/lifecycle_capsules
repository: https://github.com/BaselMoustafa/lifecycle_capsules
documentation: https://github.com/BaselMoustafa/lifecycle_capsules#readme
issue_tracker: https://github.com/BaselMoustafa/lifecycle_capsules/issues
topics:
  - lifecycle
  - capsules
  - flutter-hooks


environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
